### ISSUE TITLE
Design home webpage for destine u website

### ISSUE THREAD

**Issue by galaumang** [destine-u/destine-u.github.io#1]
## Design home webpage for Destine U website
Create a user-friendly responsive home page to communicate the brand or purpose of the website and provide easy navigation.

### Tasks
- [ ] Project setup & configuration for React Application
- [ ] Implementation of the home webpage
- [ ] Configure Github Actions & Pages
